### ISSUE TITLE
"self" is not defined when trying to use getfunctions/httpscallable API from firebase

### ISSUE THREAD

**Issue by dahburj** [jthegedus/svelte-adapter-firebase#100]
**Describe the bug**
Well I don't if it's a bug or if I'm doing something wrong, but I keep getting all these crazy errors and build fails when I try to use/import firebase functions from any client side script. I have a multitude of Firebase Functions (besides the svelte kit one) that I'd like to utilize, but I have no idea how, any help would be greatly appreciated. 

**To Reproduce**
1. Add  import { getFunctions, httpsCallable } from 'firebase/functions'; to any client side script (even firebase/compat/functions gave the same following errors)
2. Run npm run build 
3. See error
**Expected behavior**
A build success message and the ability to use firebase's httpscallable API on some client rendered scripts, like for signup/login

**Screenshots**

**Additional context**
 Error message below:
Adapter configuration:
        {"firebaseJson":"firebase.json","sourceRewriteMatch":"**"}
  Writing Cloud Function server assets to:
        functions/sveltekit
  Erasing static asset dir before processing:
        public
  Writing client application to:
        public
  Prerendering static pages to:
        public
> self is not defined
ReferenceError: self is not defined
    at file:///Users/jd/Documents/github/svelte-adapter-firebase_example/.svelte-kit/output/server/app.js:13520:30
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async prerender (file:///Users/jd/Documents/github/svelte-adapter-firebase_example/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.115_svelte@3.38.2/node_modules/@sveltejs/kit/dist/chunks/index7.js:80:14)
    at async Object.prerender (file:///Users/jd/Documents/github/svelte-adapter-firebase_example/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.115_svelte@3.38.2/node_modules/@sveltejs/kit/dist/chunks/index7.js:312:5)
    at async adapt (file:///Users/jd/Documents/github/svelte-adapter-firebase_example/node_modules/.pnpm/svelte-adapter-firebase@0.8.4_@sveltejs+kit@1.0.0-next.115/node_modules/svelte-adapter-firebase/src/index.js:51:4)
    at async adapt (file:///Users/jd/Documents/github/svelte-adapter-firebase_example/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.115_svelte@3.38.2/node_modules/@sveltejs/kit/dist/chunks/index7.js:338:2)
    at async file:///Users/jd/Documents/github/svelte-adapter-firebase_example/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.115_svelte@3.38.2/node_modules/@sveltejs/kit/dist/cli.js:656:5

**Comment by jthegedus** [comment]
Hey @dahburj, I haven't used the Client JS SDK in SvelteKit yet, but I believe you need to use it after checking that your are in a `browser` env with https://kit.svelte.dev/docs#modules-$app-env and then also `onMount` with https://svelte.dev/docs#onMount

Can you share the reason you closed this Issue?

**Comment by dahburj** [comment]
I closed it because I got it to work within half an hour of posting the issue; the steps you mention was my OG game plan, however, let's just say it was a lot easier to plan than to execute😂.. But I finally found a way to get to import into the client side without the ton of errors I kept hitting. For any/all interested; I got it to work by using the router=browser variable in each of the functions, and; more importantly, to get it to run AND build without errors I had to import the firebase modules at the beginning of each/every function. 


`
        if (router) {
   
 
        const { getFunctions, httpsCallable } = await import("firebase/functions")
        const functionsN = getFunctions()
        await signUpWithEmailPassword(signupEmail, signupPassword)
        const fCreateUser = httpsCallable(functionsN, "createUser")

        await fCreateUser({companyName: userFullName})
        .then(async(result) => {
        console.log(result)
        const data = result.data;
        console.log(data)
        notificationMessage.set({ message: 'Welcome back!', type: 'toast--link' })
        disableAction = false
        await goto('/dashboard');
        })
        .catch(function(error) {
        console.log(error)
        })
}
`

**Comment by jthegedus** [comment]
I will probably write a guide on Firebase with SSR tools once I go through the motions of getting it to work in my own apps. I currently only have the new `firebase-admin@exp` lib working in SvelteKit Endpoints, so no need for trickery checking runtimer (browser/server) or waiting for component mounts.

**Comment by jthegedus** [comment]
I will add examples to the docs as I resolve the issues - https://github.com/jthegedus/svelte-adapter-firebase/issues/101
