### ISSUE TITLE
 Cannot read property 'paths' of undefined

### ISSUE THREAD

**Issue by nielsvandermolen** [jthegedus/svelte-adapter-firebase#106]
**Describe the bug**
Using version 0.9.0 with SvelteKit Next 119. We get this ``` Cannot read property 'paths' of undefined``` error after deploying to Firebase and running the site.

**To Reproduce**
1. Deploy a website with specified versions to firebase using Firebase functions
2. Deploy should succeed
3. Go to the website on Firebase
4. White screen with error and error in the logs

**Expected behavior**
That we do not get errors on Firebase

**Screenshots**

**Additional context**

The issue is fired in this related code? (seems to be connected to Svelte hooks file:
```
function init(settings) {
  set_paths(settings.paths);
```

Maybe we forgot to implement something related to a new Adapter API?

Potentially related issue:
https://github.com/sveltejs/kit/issues/1813

**Comment by jthegedus** [comment]
Can you try with `@sveltejs/kit@1.0.0-next.120`? I mismatched my table in the readme and `0.9.0` should match `@sveltejs/kit@1.0.0-next.120`

**Comment by nielsvandermolen** [comment]
Thanks! The latest svelte kit version next.123 worked with the latest adapter version.

**Comment by jthegedus** [comment]
Great, thanks for reporting back. Sorry for initial confusion :)
