### ISSUE TITLE
RFC: Deprecate Cloud Run support

### ISSUE THREAD

**Issue by jthegedus** [jthegedus/svelte-adapter-firebase#118]
### Describe the problem

We have basic Cloud Run support, [though it may no longer be required in the near future](https://github.com/firebase/firebase-tools/pulls?q=is%3Apr+sort%3Aupdated-desc+cloud+run+is%3Aclosed).

:+1: if you agree with deprecation

:-1: if you wish to see Cloud Run support remain

**Please comment if this would be disruptive to your workflow and WHY you use Cloud Run over Functions with this Firebase Adapter**

**Comment by jquesada2016** [comment]
I personally think this would be great going forward.

**Comment by jthegedus** [comment]
> I personally think this would be great going forward.

You think deprecating Cloud Run or keeping Cloud Run would be great?

**Comment by jquesada2016** [comment]
> > I personally think this would be great going forward.
> 
> You think deprecating Cloud Run or keeping Cloud Run would be great?

I think deprecating Cloud Run would be a good idea.

**Comment by CaptainCodeman** [comment]
I can see how going with "functions" would be much simpler, but I much prefer to use cloud run

**Comment by jthegedus** [comment]
@CaptainCodeman I prefer Cloud Run too. I updated the PR with a link, I suggest you take a look.

**Comment by CaptainCodeman** [comment]
Sorry, I'm not sure I understand what link you mean and what I am meant to be looking at.

Do you mean the link at the top of this issue? That just links to a list of firebase issues:
https://github.com/firebase/firebase-tools/pulls?q=is%3Apr+sort%3Aupdated-desc+cloud+run+is%3Aclosed

**Comment by jthegedus** [comment]
Yes, I meant that link. The existence of issues matching that filter will indicate why this RFC exists.

**Comment by SrZorro** [comment]
https://github.com/jthegedus/svelte-adapter-firebase#function-vs-run

The only problem I see its that we would lose the Cold start mitigations, does the "stay tuned" in functions means there will be an equivalent for functions?

My current path its develop locally with functions to use the functions debugger, and when Im ready to deploy I was going to use cloud run to prevent cold start.

There is another way with functions? If so I would be happy to ditch cloud run.

**Comment by jthegedus** [comment]
>does the "stay tuned" in functions means there will be an equivalent for functions?

As I understand, yes.

**Comment by CaptainCodeman** [comment]
Cloud Run has another _significant_ benefit over cloud functions.

The default concurrency is 80 requests per instance and it can be configured as high as 1,000

Cloud functions on the other hand has a limit of ... drum roll ... 1. Yes one concurrent request per instance.

I think if you're doing anything non-trivial there should be benefits to using Cloud Run.

**Comment by jthegedus** [comment]
Cloud Functions now has `min_instances` support.

Official release blog post - https://cloud.google.com/blog/products/serverless/cloud-functions-supports-min-instances

Firebase supports this in https://github.com/firebase/firebase-functions/releases/tag/v3.15.5

You can use it like so:

```diff
const myOpts = {
	memory: "1GB",
+	min_instances: 1,
}
exports.myFunc = functions.runWith(myOpts).https.onRequest(async (request, response) => {
	...
});
```

Also Node.js 16 is available as of https://github.com/firebase/firebase-tools/releases/tag/v9.17.0
