### ISSUE TITLE
Package subpath './http' is not defined by "exports" in /workspace/node_modules/@sveltejs/app-utils/package.json

### ISSUE THREAD

**Issue by jdgamble555** [jthegedus/svelte-adapter-firebase#12]
It seems the latest version **1.0.0-next.1** changed the way it exports.  It seems to be a problem with:

```typescript
const {get_body: getBody} = require('@sveltejs/app-utils/http');
```
in **handler.js**

**Comment by jthegedus** [comment]
Thanks for raising this, I will take a look.

The 3 new versions since I last tested this are:
- `1.0.0-next.32`
- `1.0.0-next.33`
- `1.0.0-next.34`

I'm going to add the "validated with" version in the README so people know which version to pin to that this adapter will work with.

**Comment by jthegedus** [comment]
After looking at the updates I see you were talking about `@@sveltejs/app-utils@1.0.0-next.1`

**Comment by jthegedus** [comment]
It seems the `app-utils` package is ESM only(?) now. Error when changing to ES module import syntax

```
 import {get_body: getBody} from '@sveltejs/app-utils/http' ^^^^^^ SyntaxError: Cannot use import statement outside a module at wrapSafe (internal/modules/cjs/loader.js:1052:16) at Module._compile (internal/modules/cjs/loader.js:1100:27) at Module._compile (pkg/prelude/bootstrap.js:1281:32) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10) at Module.load (internal/modules/cjs/loader.js:984:32) at Function.Module._load (internal/modules/cjs/loader.js:877:14) at Module.require (internal/modules/cjs/loader.js:1024:19) at Module.require (pkg/prelude/bootstrap.js:1225:31) at require (internal/modules/cjs/helpers.js:72:18)
```

I am no esm expert, especially when it comes to Node.js environments. This was on a Node.js 14.15.3 Firebase emulator Function, I will have to investigate further :thinking:

**Comment by jthegedus** [comment]
When the node adapter moves to `latest` tag I will address this.
![Screenshot from 2021-02-12 07-55-08](https://user-images.githubusercontent.com/20798510/107697713-ae377200-6d07-11eb-97eb-39951c00fd8e.png)

In the meantime, please use `@sveltejs/kit@1.0.0-next.31`, `.33` may work, but I have not tested it

**Comment by jthegedus** [comment]
This still won't actually work, but for different reasons, see #16
