### ISSUE TITLE
Update `rawBody`

### ISSUE THREAD

**Issue by benmccann** [jthegedus/svelte-adapter-firebase#122]
### Describe the Bug

See https://github.com/sveltejs/kit/pull/2215

You'll need to update https://github.com/jthegedus/svelte-adapter-firebase/blob/52429d23809c08dd8027e6b0ce8c2e04b6b41136/src/files/handler.js#L23

This is the last breaking change on the 1.0 milestone affecting SvelteKit adapters, so while no promises, hopefully there won't be any more changes required after this

Thanks for providing this adapter!

### Steps to Reproduce

look at source code

### Expected Behaviour

uses latest SvelteKit API

### svelte-adapter-firebase version

n/a

### sveltejs/kit version

latest

**Comment by jthegedus** [comment]
will get on this soon, thanks for the report :+1:

**Comment by jthegedus** [comment]
@benmccann I want to type `render` from `import {init,render} from '../output/server/app.js';` to ensure my adapter matches the correct types, is this possible? I am unsure if `App.init` and `App.render` are the correct types and if they can/should be exposed?

**Comment by jthegedus** [comment]
Thanks for your help on this :pray: Hopefully my new rawBody code is correct :sweat_smile:
