### ISSUE TITLE
bug: target property is not being applied correctly

### ISSUE THREAD

**Issue by vpanyushenko** [jthegedus/svelte-adapter-firebase#148]
### Describe the Bug

When deploying with multiple targets, you get the error: 

> Error: Multiple "hosting" configurations found, but no "target" specified in "svelte.config.js" adapter config. Provide one so we can match the config correctly.

### Steps to Reproduce

1. Have a multi site setup in firebase.json using targets
2. Specify the target in the adapter preferences (my svelte.config.js file was in a nested folder not the root)

### Expected Behaviour

Should build successfully.

Seems like the adapter is still looking for `hostingSite` on lines 23 and 31 of `index.js`. By adding `target = undefined` into the `options` object and swapping `hostingSite` for `target`, the issue gets resolved. 

### svelte-adapter-firebase version

0.13.0

### sveltejs/kit version

1.0.0-next.180

**Comment by jthegedus** [comment]
Thanks for the thorough bug report, I have fixed this issue and updated my tests to capture this in future :pray:
