### ISSUE TITLE
bug: npm run build error

### ISSUE THREAD

**Issue by mulllhausen** [jthegedus/svelte-adapter-firebase#154]
I have a problem when running `npm run build` - it gives an error. Here is my firebase.json:

```
{                                                                               
  "functions": {                                                                
    "source": "functions",                                                      
    "predeploy": [                                                              
      "npm --prefix \"$RESOURCE_DIR\" run lint",                                
      "npm --prefix \"$RESOURCE_DIR\" run build"                                
    ]                                                                           
  },                                                                            
  "database": {                                                                 
    "rules": "database.rules.json"                                              
  },                                                                            
  "firestore": {                                                                
    "rules": "firestore.rules",                                                 
    "indexes": "firestore.indexes.json"                                         
  },                                                                            
  "hosting": {                                                                  
    "public": "public",                                                         
    "rewrites": [{                                                              
        "source": "**",                                                         
        "function": "svelteSSR"                                                 
    }],                                                                         
    "ignore": [                                                                 
      "firebase.json",                                                          
      "**/.*",                                                                  
      "**/node_modules/**"                                                      
    ]                                                                           
  },                                                                            
  "storage": {                                                                  
    "rules": "storage.rules"                                                    
  },                                                                            
  "emulators": {                                                                
    "auth": {                                                                   
      "port": 9099                                                              
    },                                                                          
    "functions": {                                                              
      "port": 5001                                                              
    },                                                                          
    "firestore": {                                                              
      "port": 8080                                                              
    },
    "database": {                                                               
      "port": 9000                                                              
    },                                                                          
    "hosting": {                                                                
      "port": 5000                                                                                
    },                                                                          
    "pubsub": {                                                                 
      "port": 8085                                                              
    },                                                                          
    "storage": {                                                                
      "port": 9199                                                              
    },                                                                          
    "ui": {                                                                     
      "enabled": true                                                           
    }                                                                           
  },                                                                            
  "remoteconfig": {                                                             
    "template": "remoteconfig.template.json"                                    
  }                                                                             
}
```

Then when I run `npm run build` i get:

```
> Error reading Cloud Function entrypoint file: /[project path]/functions/lib/index.js. ENOENT: no such file or directory, open '/[project path]/functions/lib/index.js'
Error: Error reading Cloud Function entrypoint file: /[project path]/functions/lib/index.js. ENOENT: no such file or directory, open '/[project path]/functions/lib/index.js'
    at adapt (file:///[project path]/node_modules/svelte-adapter-firebase/src/index.js:87:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async adapt (file:///[project path]/node_modules/@sveltejs/kit/dist/chunks/index4.js:388:2)
    at async file:///[project path]/node_modules/@sveltejs/kit/dist/cli.js:891:5
```

However I can see that it has created a new dir and file at `functions/lib/svelteSSR/index.js`. I initially selected to use typescript when I set up sveltekit, I wonder if that is a problem.

How can I fix the `npm run build` error?

**Comment by jthegedus** [comment]
Thanks for making a new Issue.

TypeScript in SvelteKit shouldn't matter as the SSR output is still a single JavaScript file.

TypeScript in Cloud Functions does matter though, and by looking at your `firebase.json` it seems you're using TS CFs.

The short answer is you need to **build your TypeScript Cloud Functions before your SvelteKit app**.

For more information please read the [How it Works](https://github.com/jthegedus/svelte-adapter-firebase#how-it-works) section in the README. Once you've read that and it's TypeScript section I am happy to answer any follow up questions

**Comment by mulllhausen** [comment]
OK cool. I just created a blank file at `functions/lib/index.js` then ran `npm run build` again. Now it is working (last line reads `✔ done`) and it has given me the instructions for what to add to `functions/lib/index.js`.

Out of curiosity, how can you tell that my `firebase.json` file is configured for typescript?

Also, if you like, I can change the title to something more appropriate. I'm so new to this that I didn't know what to call it. What would you suggest?

**Comment by jthegedus** [comment]
>OK cool. I just created a blank file at `functions/lib/index.js`

This isn't the correct path forward. More below.

>Out of curiosity, how can you tell that my `firebase.json` file is configured for typescript?

There's not many reasons to have `predeploy` steps for `functions`, especially `npm --prefix \"$RESOURCE_DIR\" run build`, unless you're compiling your code. Also, `functions/lib/index.js` is computed from your codebase and `functions/lib` is a TypeScript pattern.

>Also, if you like, I can change the title to something more appropriate. I'm so new to this that I didn't know what to call it. What would you suggest?

That's not necessary. Something like `Error reading Cloud Function entrypoint file: /[project path]/functions/lib/index.js. ENOENT: no such file or directory`

---

For the adapter to know where to write your SSR code output, it reads your `functions/package.json` `main` field to determine the output location. In a Cloud Function TypeScript setup you usually have this structure:

```
functions/
  package.json ("main": "lib/index.js")
  src/
    index.ts
  lib/
    index.js    <-- compiled TS entrypoint
    sveltekit/	<-- Server assets output to functions/lib
yourApp/		<-- Static assets to go to Firebase Hosting CDN
```

We see `functions/lib/index.js` in the `package.json` and so write our SSR code to `functions/lib` dir :heavy_check_mark: 

After we output this, we want to log the Cloud Function http code for you to accept requests and forward them to the SvelteKit app, but we don't want to spam you if you've already done this, so we look through the file we expect to find this code. In a TS CF setup that is in `lib/index.js`, not `src/index.ts`. This is the piece that threw an error for you :x: because `lib/index.js` did not exist yet, so **running your Cloud Function `build` script** is what you want to do to create the `index.js` file. It will probably require adding the CLI output to your `lib/index.js` each time you build your TypeScript.

This situation isn't ideal, the error could be better. Requiring the TypeScript Cloud Function build first is also poor ergonomically (I need to explore the TypeScript Cloud Function solution further).

**Comment by cBiscuitSurprise** [comment]
Thanks @jthegedus this was helpful. The steps I followed:

* add the function you output on the terminal to `functions/src/index.ts`
* update `functions/package.json` to add `"main": "lib/index.js"`
* then add to my root `package.json`: 
    ```json
      "scripts": {
        "build": "cd functions && npm run build && cd .. && svelte-kit build",
        ...
    ```

Then future `npm run build` at the root-level does all the right stuff (it first builds `functions/lib/index.js` with your SSR method, then builds the SSR artifacts).

😎

**Comment by Nushio** [comment]
We just released a new version. I'll close this issue as it seems resolved, but feel free to open one up if this or a similar issue happens again.
