### ISSUE TITLE
bug: SvelteKit v1.0.0-next-382 removed `writeStatic` causes build to break

### ISSUE THREAD

**Issue by pham** [jthegedus/svelte-adapter-firebase#172]
### Describe the Bug

SvelteKit removed `writeStatic` to align with Vite [#5618](https://github.com/sveltejs/kit/pull/5618).

Build output:
```
> Using svelte-adapter-firebase
error during build:
Error: writeStatic has been removed. Please ensure you are using the latest version of svelte-adapter-firebase
```

### Steps to Reproduce

```
npx vite build
```

### Expected Behaviour

Output should look like:
```
> Using svelte-adapter-firebase
  ✔ done
```

### svelte-adapter-firebase version

0.14.1

### sveltejs/kit version

1.0.0-next-382

**Comment by x-o1d** [comment]
same issue with sveltekit 405, but commenting out https://github.com/jthegedus/svelte-adapter-firebase/commit/9a990a00667b5f2197915d8b380593a5a05d306b works.
any idea when 0.14.2 will be released?
