### ISSUE TITLE
📣 Syncing with Kit on it's way to `v1.0`

### ISSUE THREAD

**Issue by jthegedus** [jthegedus/svelte-adapter-firebase#179]
Kit is moving towards `1.0` very quickly with lots of breaking changes. Multiple releases are happening each day with many breaking changes day to day at the moment.

I will do my best to update this repos compatibility about once per week.

Most of the changes shouldn't affect this adapter, but if they do, you should see a fix from me shortly.

Thanks for your use of the adapter and see #162 for some of the larger Firebase features we intend to integrate with in the near future.

**Comment by Nushio** [comment]
New from Svelte Summit Fall. Sveltekit is entering it's release candidate phase! That means no more breaking changes! 🥳

**Comment by Antonio-Bennett** [comment]
@Nushio *Planned breaking changes

**Comment by jthegedus** [comment]
I have been very poor at sticking with this commitment. Hopefully Kit `v1.0` will release soon so I can update the adapter without further breaking changes. It has been nearly 2 years since I foolishly started this repo 🙄

**Comment by jthegedus** [comment]
Syncing with Kit `1.0.0` took much more effort than I had time over the holiday period, thanks to @pham in #201 we have `kit@1.1.1` support with [`svelte-adapter-firebase@0.15.0`](https://github.com/jthegedus/svelte-adapter-firebase/releases/tag/v0.15.0)

I will close this Issue. #162 is still an area of interest to me so follow there for updates with newer Firebase features. I also have a lot of work to do with documentation.

Thanks for your patience with this `kit@1.0.0` support and many thanks to @pham for getting it across the line 🙏
