### ISSUE TITLE
docs: Clean up README

### ISSUE THREAD

**Issue by DestroyerXyz** [jthegedus/svelte-adapter-firebase#182]
### Describe the Bug

The README is really confusing and all over the place. It is really difficult to understand the process of setting up the project.

### Steps to Reproduce

Go to project page on Github.

### Expected Behaviour

Please clean up the docs and create a step-by-step guide to set up the project, with examples.

### svelte-adapter-firebase version

0.14.2

### sveltejs/kit version

1.0.0-next.405

**Comment by jthegedus** [comment]
They are out of date and there is a lot going on, yes. Much to improve. Are you able to give more specific feedback as to which aspects you found confusing? The *Setup* section has 4 dot points to follow, which parts are not clear?
