### ISSUE TITLE
bug: [breaking change] getStaticDirectory() removal

### ISSUE THREAD

**Issue by mjh316** [jthegedus/svelte-adapter-firebase#191]
### Describe the Bug

In [here](https://github.com/jthegedus/svelte-adapter-firebase/blob/main/src/index.js), there is one usage of getStaticDirectory(), whose removal has been [proposed](https://github.com/sveltejs/kit/issues/7800). Would the firebase adapter be able to use something else to achieve this same behavior? (This is a breaking change targeting the SvelteKit 1.0 milestone).

### Steps to Reproduce

1. Go [here](https://github.com/jthegedus/svelte-adapter-firebase/blob/main/src/index.js)
2. Observe the builder.getStaticDirectory() call.

### Expected Behaviour

Ideally, identify the use case and find an alternative(s).

### svelte-adapter-firebase version

0.9.2

### sveltejs/kit version

1.0.0-next.128

**Comment by jthegedus** [comment]
Closed in #193
