### ISSUE TITLE
bug: Generated index.js file goes into wrong folder

### ISSUE THREAD

**Issue by kkharkov** [jthegedus/svelte-adapter-firebase#207]
### Describe the Bug

Not sure if this is bug, feature, or oversight, but basically I have the entire project setup and working, except when I type `npm run build` it results in this error:
```
Error: Error reading Cloud Function entrypoint file: /home/kk/Documents/GW/CAPSTONE/link/functions/lib/index.js. ENOENT: no such file or directory, open '/home/kk/Documents/GW/CAPSTONE/link/functions/lib/index.js'
```

Which comes from the fact that the SvelteKit adapter (or firebase?) expects the file to be in `functions/lib/index.js` but instead is being placed within an extra lib folder making the path `functions/lib/functions/index.js` causing the issue. Also based off the documentation index.js should be printed to the console which is not the behavior I am seeing either.
Main is correctly defined in the functions specific package.json. Moving the `index.js` into the expected directory seemingly fixes the issue.

Below is my firebase.json
```
{
  "functions": 
    {
      "source": "functions",
      "codebase": "default",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log"
      ],
      "predeploy": [
        "npm run lint",
        "npm run build"
      ]
    },
  "hosting": {
    "public": "public",
    "rewrites": [
      {
        "source": "**",
        "function": "functions"
      }],
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```

And my svelte.config.js (I tried with and without a target)
```
import firebase from 'svelte-adapter-firebase';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
	// for more information about preprocessors
	preprocess: vitePreprocess(),

	kit: {
		adapter: firebase({target: 'functions'})
	}
};

export default config;
```

### Steps to Reproduce

1. Add SvelteKit Firebase adapter to existing SvelteKit project.
2. Setup Firebase
3. `npm run build` the project

### Expected Behaviour

As far as I understand I should just be able to `npm run build` and the index.js should be generated in the correct directory (functions/lib/) OR be printed to the console, like is described in the documentation.

### svelte-adapter-firebase version

0.15.0

### sveltejs/kit version

1.1.1

**Comment by lewis-elborn** [comment]
Also experiencing this. 😅

**Comment by kkharkov** [comment]
I'm stupid, I had my rewrites and functions names the same. Changing this produced the expected behavior.
