### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by Malix-Off** [jthegedus/svelte-adapter-firebase#209]
## Subject

https://github.com/jthegedus/svelte-adapter-firebase/blob/d5e9691b131473c5277a97c09d7563d618a33f5b/README.md?plain=1#L84-L87

## Reason

[SvelteKit is no more in beta](https://svelte.dev/blog/announcing-sveltekit-1.0)

**Comment by jthegedus** [comment]
Resolved in https://github.com/jthegedus/svelte-adapter-firebase/commit/c7a56cb4187b6f4f90aecb212e0b731e78c009ce
