### ISSUE TITLE
bug: Duplicate copy of `_app` on build

### ISSUE THREAD

**Issue by jthegedus** [jthegedus/svelte-adapter-firebase#22]
**Describe the bug**

A second copy of the `_app` dir is created under `.svelte/output/client/` and then copied on build to the adapter output.

**To Reproduce**

Reproduction repo here - https://github.com/jthegedus/sveltekit-firebase-adapter-bug

**Expected behavior**

It does not create duplicate `_app` dirs.

**Comment by jthegedus** [comment]
This could be related - https://github.com/sveltejs/kit/issues/587 :thinking:

**Comment by jthegedus** [comment]
Could be related - https://github.com/sveltejs/kit/issues/861

**Comment by jthegedus** [comment]
It is https://github.com/sveltejs/kit/issues/587

**Comment by jthegedus** [comment]
#39 included some documentation to notify users. A final soln in https://github.com/sveltejs/kit/issues/587 would be ideal

**Comment by Nushio** [comment]
As of the latest sveltekit / sveltekit adapter firebase, we're no longer using a duplicate copy of _app.
I'll go ahead and close this issue.

**Comment by jthegedus** [comment]
Resolved in https://github.com/sveltejs/kit/pull/4214

There is some code which should be removed to accompany this change. I will look to cover this in a rewrite soon.
