### ISSUE TITLE
Svelte App in subdirectory

### ISSUE THREAD

**Issue by lschmierer** [jthegedus/svelte-adapter-firebase#33]
**Describe the bug**
The functions folder is not correctly resolved relative to firebase.json, when the Svelte app is placed in a subdirectory.

```
> ENOENT: no such file or directory, open 'functions/package.json'
```

The example in the README does not work.
https://github.com/jthegedus/svelte-adapter-firebase/blob/main/README.md#adapter-configurations

**To Reproduce**
1. Place the Svelte Kit application in subfolder, e.g. `svelte_app`.
2. Configure Svelte adapter `adapter: firebaseAdapter({ firebaseJson: "../firebase.json" }),`

**Expected behavior**
`package.json` should be looked for at `../functions/package.json` instead of `functions/package.json`.

**Comment by lschmierer** [comment]
Hosting deployment has the same issue

**Comment by jthegedus** [comment]
>Hosting deployment has the same issue

can you clarify what you mean by this?

**Comment by lschmierer** [comment]
If i remember correctly, the hosting deployment folder was resolved relative to the svelte project instead of relative to the firebase.json file.

**Comment by jthegedus** [comment]
Ah, yes, you're correct. I am addressing this now treating the `firebase.json` as the root. Watch for the next release.
