### ISSUE TITLE
Support `target` in `firebase.json` configuration.

### ISSUE THREAD

**Issue by kfowler** [jthegedus/svelte-adapter-firebase#36]
**Is your feature request related to a problem? Please describe.**
We have one source base deployed into two firebase projects as described [here](https://firebase.google.com/docs/hosting/multisites) each with two sites. `firebase.json` includes a `target` which identifies the site after running `firebase target:apply hosting TARGET_NAME RESOURCE_IDENTIFIER`.

**Describe the solution you'd like**
We'd like to specify `target` in `svelte.config.cjs` instead of `hostingSite`:
```
module.exports = {
	preprocess: sveltePreprocess(),

	kit: {
		adapter: firebaseAdapter({firebaseJson: '../firebase.json', target: "fungi"}),
```
**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jthegedus** [comment]
@kfowler Is `target` strictly used **instead** of `site` in `firebase.json`, or are there situations whereby both can be used in a single site's config?

**Comment by vpanyushenko** [comment]
You cannot have both `site` and `target` in the `firebase.json` so whatever key we go with, you could just check for either `target` or `site`. `target` is the way that the firebase docs generally want you to work with multiple hosting sites, from my experience working with it.

But to match the `firebase.json` schema, it might make sense to include both `site` and `target`, just like firebase does and throw an error if the user includes both.

**Comment by jthegedus** [comment]
I am working on a solution to this now, sorry for the delay.

**Comment by jthegedus** [comment]
The adapter should now read the `target` field from your `firebase.json` configs.

I have noted in the [Caveats](https://github.com/jthegedus/svelte-adapter-firebase#caveats) section that while we will use the `target` value to identify the Hosting config, you cannot use [Deploy Targets](https://firebase.google.com/docs/cli/targets) to deploy to Firebase as it will not deploy Functions, which is obviously required with this SSR solution.
