### ISSUE TITLE
Svelte Fetch is not included on the Firebase build

### ISSUE THREAD

**Issue by nielsvandermolen** [jthegedus/svelte-adapter-firebase#37]
**Describe the bug**
The todo page does not work when deploying the demo example project on Firebase with this adapter. It will throw: `ReferenceError: fetch is not defined`

**To Reproduce**
deploy the demo application on Firebase and go to the todos page

**Expected behavior**

That the fetch calls to the external API would work and no errors are thrown.

**Screenshots**

**Additional context**

There is some recent work in the official adapters to support Fetch
https://github.com/sveltejs/kit/pull/1066
https://github.com/sveltejs/kit/pull/1091

I am not sure if the solution is to ``import '@sveltejs/kit/install-fetch' or that we have to do something with `node-fetch` 
https://github.com/sveltejs/kit/issues/618#issuecomment-822474031

**Comment by jthegedus** [comment]
Current SvelteKit version support is `@svelte/kit@1.0.0-next.54`, I am updating to `@svelte/kit@1.0.0-next.94` atm and will include this fix.

I will also put a adapter version <--> sveltekit version table in the repo so people are aware.
