### ISSUE TITLE
Container crashes on cloud run

### ISSUE THREAD

**Issue by nhe23** [jthegedus/svelte-adapter-firebase#38]
Container crashes on cloud run

**To Reproduce**
- Use SvelteKit v1.0.0-next.94 and the current version of svelte-adapter-firebase.
- Build the SvelteKit demo app with firebase adapter (for cloud run)
- Deploy the demo app to cloud run with ```gcloud beta run deploy mysitessr --platform managed --region us-central1 --source .mysitessr --allow-unauthenticated```
- Goto /todos on the deployed app -> 500 error in the client and ```Cannot find package '@sveltejs/kit' imported from /workspace/app.mjs``` in the cloud run logs (detailed logs in the screenshot below)

This was also reproducible with other projects than the demo app. There the ```Cannot find package '@sveltejs/kit' imported from /workspace/app.mjs``` was returned back to the client.

**Expected behavior**
Container should work and not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/19340684/116776197-6f43cd80-aa67-11eb-8f33-fe7c83a086ca.png)

**Comment by jthegedus** [comment]
Current SvelteKit version support is `@svelte/kit@1.0.0-next.54`, I am updating to `@svelte/kit@1.0.0-next.94` atm.

Once the new version is released you can test again.
