### ISSUE TITLE
Module not installable with npm 

### ISSUE THREAD

**Issue by nhe23** [jthegedus/svelte-adapter-firebase#44]
**Describe the bug**
Current version 0.6.1 is not installable with npm. When I use pnpm it works. However the container does not build on CloudRun because it also has this problem.

**To Reproduce**
1. Initialize svelte kit demo app
2. Add "svelte-adapter-firebase": "^0.6.1" as devDependency in package.json
3. run ```npm i```

**Expected behavior**
npm install should work and container should build on CloudRun

**Screenshots**
![image](https://user-images.githubusercontent.com/19340684/117280177-a00a7500-ae62-11eb-8a44-c4265d347d76.png)
![image](https://user-images.githubusercontent.com/19340684/117299885-4a8d9280-ae79-11eb-895a-1730f76a73f8.png)

**Comment by nhe23** [comment]
Another thing I found:
![image](https://user-images.githubusercontent.com/19340684/117300380-c8519e00-ae79-11eb-93c3-a342829b649d.png)

This can be reproduced by using the sveltekit demo app and using the 'svelte-adapter-firebase' adapter in the current version. When I copied the package.json ('my-app/node_modules/.pnpm/svelte-adapter-firebase@0.6.1_svelte@3.38.2+vite@2.2.4/node_modules/svelte-adapter-firebase/package.json) to 'my-app/node_modules/.pnpm/svelte-adapter-firebase@0.6.1_svelte@3.38.2+vite@2.2.4/node_modules/svelte-adapter-firebase/src/package.json' the error disappeared. But the deployment to cloud run did not work after that because of the error described in this issue. @jthegedus Should I add a separate issue for this?

**Comment by jthegedus** [comment]
> Should I add a separate issue for this?
I think this will be the result of the same issue. I thought i was able to force development to occur with `pnpm`, but that has obviously affected CloudBuild build step which with Buildpacks always uses `npm`

I will fix momentarily.

**Comment by jthegedus** [comment]
@nhe23 You will need to test Cloud Run with the changes in `0.6.2` when `0.6.3` (fix for this) releases.

**Comment by jthegedus** [comment]
I will work on #24 next so these types of issues get caught sooner. Apologies :pray:

**Comment by nhe23** [comment]
> @nhe23 You will need to test Cloud Run with the changes in `0.6.2` when `0.6.3` (fix for this) releases.

I just installed the new version and it is now installable with npm. However running ```npm run build```causes the following error:
![image](https://user-images.githubusercontent.com/19340684/117426972-cf81b600-af24-11eb-87f5-83076fde66f8.png)

**Comment by jthegedus** [comment]
@nhe23 I missed some commits in #43 which had the fix for your issue, sorry about that. New release should have the fix.

**Comment by jthegedus** [comment]
@nhe23 I'll get this right eventually, try that new version.
