### ISSUE TITLE
Cannot install version 0.6+ with npm

### ISSUE THREAD

**Issue by nielsvandermolen** [jthegedus/svelte-adapter-firebase#45]
**Describe the bug**
After installing with npm the following bug is triggered.

```
npm ERR! command sh -c npx -y only-allow pnpm                                                    
npm ERR! ║   Use "pnpm install" for installation in this project.                                              
npm ERR! ║   If you don't have pnpm, install it via "npm i -g pnpm".  
npm ERR! ║   For more details, go to https://pnpm.js.org/
```

**To Reproduce**
 npm install --save-dev svelte-adapter-firebase@0.6.1

**Expected behavior**
The adapter should be able to be installed with npm 

**Additional context**
It seems pnpm can not do anything npm can not do besides being a bit more efficient in caching. Therefore pnpm should not be a requirement to install the adapter?

This line in package.json is causing the issue:
```
  "scripts": {
    "preinstall": "npx -y only-allow pnpm",
 ```

**Comment by nielsvandermolen** [comment]
I should read better duplicate of https://github.com/jthegedus/svelte-adapter-firebase/issues/44

**Comment by jthegedus** [comment]
Please try `0.6.3` as I believe this has been fixed.
