### ISSUE TITLE
Cloud Run container can't be deployed because of devDependencies

### ISSUE THREAD

**Issue by nhe23** [jthegedus/svelte-adapter-firebase#54]
**Describe the bug**
Cloud Run Container does not start because of several issues with dependencies/scripts.

**To Reproduce**
1.Initialize svelte kit demo app
2. Add "svelte-adapter-firebase": "^0.6.3" as devDependency in package.json and configure the adapter as described in the docs
3. npm i
4. fix #53 locally & build the project
5. deploy to cloud run

**Expected behavior**
Cloud Run container should start

**Screenshots**
![image](https://user-images.githubusercontent.com/19340684/117798340-57cbc800-b251-11eb-801b-8cb7068d112a.png)

**Additional context**
Removing the devDependencies from the generated package.json in .mysitessr and removing all scripts but the 'start' script seem to fix this problem (At least the container is deployed).

**Comment by jthegedus** [comment]
The bug here is that the wrong `package.json` is being detected and used. Fix incoming.

**Comment by jthegedus** [comment]
Fixed in #52
