### ISSUE TITLE
Only file and data URLs are supported by the default ESM loader.

### ISSUE THREAD

**Issue by dalsochio** [jthegedus/svelte-adapter-firebase#70]
**I'm having trouble running "npm run build" on my Windows.**

**How do I solve this?**

_Just testing "svelte-adapter-firebase/examples/functions_single_site /"._ 

> > Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'p:'
> Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'p:'
>     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
>     at Loader.resolve (internal/modules/esm/loader.js:86:40)
>     at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
>     at Loader.import (internal/modules/esm/loader.js:165:28)
>     at importModuleDynamically (internal/modules/esm/translators.js:114:35)
>     at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
>     at adapt (file:///P:/LEFRANK/kit-firebase/node_modules/svelte-adapter-firebase/src/index.js:28:43)
>     at adapt (file:///P:/LEFRANK/kit-firebase/node_modules/@sveltejs/kit/dist/chunks/index5.js:322:8)
>     at file:///P:/LEFRANK/kit-firebase/node_modules/@sveltejs/kit/dist/cli.js:616:11

**Comment by jthegedus** [comment]
I haven't yet added Windows support. I will look into solving this weekend, thanks for reporting.
