### ISSUE TITLE
Call to getRawBody waits indefinitely in handler.js

### ISSUE THREAD

**Issue by AndrewLester** [jthegedus/svelte-adapter-firebase#87]
**Describe the bug**
The call to `getRawBody` in handler.js waits indefinitely when the request body is not undefined. This causes the SSR cloud function to stall and timeout when trying to render a route if the incoming request has a body.
https://github.com/jthegedus/svelte-adapter-firebase/blob/e3d32e4a004f16f56ae2cb21b5c143be9e2aadc8/src/files/handler.js#L17

**To Reproduce**
Create an endpoint that exports a `post` function, and try to access the `body` property of the LoadInput object. You'll find that the endpoint function never actually runs, when a request has a body, because it is never able to. I've only tested this in firebase cloud functions.

**Expected behavior**
The endpoint function gets run properly and can access the body of the request.

**Additional context**
The reason that the infinite await occurs is because `getRawBody` expects an [IncomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage) object, but it receives a [Request](https://expressjs.com/en/5x/api.html#req) object. This is due to Firebase's differences from other hosting services.

I have created a bad fix for this that only allows JSON data through, but you can see the premise of the solution:
https://github.com/AndrewLester/svelte-adapter-firebase/blob/c90d75dbd67a7652244f38dfd53548d8c3d24bd2/src/files/handler.js#L16

**Comment by jthegedus** [comment]
Thanks for reporting. I am not sure what functionality is captured in `getRawBody` so will need to investigate.

You are right that it is unique to Firebase. The parsing Firebase performs is captured in the docs here - https://firebase.google.com/docs/functions/http-events#read_values_from_the_request - so will need to be compared. It may just be a matter of reverting the parsing Firebase performs to hand the raw to SvelteKit.

Let the platform specific implementation commence! :sweat_smile:

**Comment by daylilyfield** [comment]
I have the same issue. 

Cloud Functions for Firebase parses request body automatically as @jthegedus mentioned above.  

>  It may just be a matter of reverting the parsing Firebase performs to hand the raw to SvelteKit.

I  agree with you, so I make a PR.

https://github.com/jthegedus/svelte-adapter-firebase/pull/93

I hope this will help.

**Comment by jthegedus** [comment]
Please retry with the latest versions of this adapter **& SvelteKit**.
