### ISSUE TITLE
Error adding adapter: Malformed svelte.config.js SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by opensas** [jthegedus/svelte-adapter-firebase#89]
**Describe the bug**

When I add the line `import firebase from "svelte-adapter-firebase";` I get the following error:

```
Malformed svelte.config.js
SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
```

**To Reproduce**

```shell
$ npm init svelte@next sveltekit-firebase-test
```

In package.json fix the @sveltejs/kit version

```json
  "devDependencies": {
    "@sveltejs/kit": "1.0.0-next.107",
```

```shell
$ npm install

$ firebase init

$ npm install --save-dev svelte-adapter-firebase
```

Add the line

```javascript
import firebase from "svelte-adapter-firebase";
```

at the beginning of svelte.config.js

run `npm run build`

```
$ npm run build

> ~TODO~@0.0.1 build /home/sas/devel/apps/glas-it/apps/keyosk/tmp/sveltekit-firebase-test
> svelte-kit build

Malformed svelte.config.js
SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ~TODO~@0.0.1 build: `svelte-kit build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ~TODO~@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sas/.npm/_logs/2021-05-25T20_59_11_043Z-debug.log
```

**Expected behavior**

The build to run ok

**Additional context**

package.json

```javascript
{
  "name": "~TODO~",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview"
  },
  "devDependencies": {
    "@sveltejs/kit": "1.0.0-next.107",
    "svelte": "^3.34.0",
    "svelte-adapter-firebase": "^0.7.7"
  },
  "type": "module",
  "dependencies": {
    "@fontsource/fira-mono": "^4.2.2",
    "@lukeed/uuid": "^2.0.0",
    "cookie": "^0.4.1"
  }
}
```

```shell
$ node --version
v12.22.1

$ npm --version
6.14.12
```

> Note: there's a github repo with the example producing the above erro at https://github.com/opensas/sveltekit-firebase-adapter-error

**Comment by opensas** [comment]
It happens with node version 12 (which is the recommended node version for firebase: https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version)

With node 14.17.0 it works. The source seems to be using the `?.` operator which is not supported by node 12

**Comment by jthegedus** [comment]
This adapter currently forces you use Node.js 14 Functions for SvelteKit.

I may look at reducing this to 12 if possible. And even if not, the error should be better.

Thanks for reporting. I will look to resolve sometime this week. Please use Node.js 14 in the meantime.

**Comment by jthegedus** [comment]
`functions init` now defaults to Node.js 14 - https://github.com/firebase/firebase-tools/releases/tag/v9.12.0

**Comment by jthegedus** [comment]
I added min Node.js versions to `package.json`. These are the same as SvelteKit except for Node.js 12 as I don't want to have to compile the adapter (can be convinced otherwise, but the debug experience is much nicer atm).
