### ISSUE TITLE
Cannot make the SvelteKit default demo application to run on firebase: timeout when POSTing a new todo

### ISSUE THREAD

**Issue by opensas** [jthegedus/svelte-adapter-firebase#90]
**Describe the bug**

After creating a new SvelteKit project with the default demo app, intialized and firebase (`firebase init`) and installed the svelte-adapter-firebase, the ssrServer functions dies with a timeout error on the logs.

**To Reproduce**

Create a new SvelteKit Application, 

```shell
npm init svelte@next adapter-error`
cd adapter-error
npm install
```

Choose **SvelteKit demo app** and leave all the other options by default

Go to firebase console and create a new project (https://console.firebase.google.com/), unselect google analytics

Add a web app **adapter-error-app**

Install firebase-tools

```
npm install -g firebase-tools@9.11.0
```

> Got a nasty error using the lastest version: firebase-tools@9.12.0

```
firebase init
```

choose functions and hosting

use an existing project, and choose the one you created before

accept all options by default

> Note: check that the node version in function/package.json is **14**

install the adapter:

```
npm install --save-dev svelte-adapter-firebase
```

update svelte.config.js

```
import firebase from "svelte-adapter-firebase";

/** @type {import('@sveltejs/kit').Config} */
export default {
  kit: {
    adapter: firebase(),
    target: "#svelte",
  },
};
```

update package.json

```
	"scripts": {
		"dev": "svelte-kit dev",
		"build": "npx rimraf myApp && svelte-kit build --verbose"
  }
```

update firebase.json

```
{
  "hosting": {
    "public": "myApp",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "function": "ssrServer"
      }
    ],
    "predeploy": ["npm run build"]
  },
  "functions": {
    "source": "functions"
  }
}
```

Deploy your app

```
firebase deploy
```

Follow the message on the terminal and add the following code to functions/index.js

```javascript
  let ssrServerServer;
  exports.ssrServer = functions.https.onRequest(async (request, response) => {
        if (!ssrServerServer) {
                functions.logger.info("Initializing SvelteKit SSR Handler");
                ssrServerServer = require("./ssrServer/index").default;
                functions.logger.info("SvelteKit SSR Handler initialised!");
        }
        functions.logger.info("Requested resource: " + request.originalUrl);
        return ssrServerServer(request, response);
  });
```

Remember to change your plan to Blaze (pay-as-you-go) 

Deploy your app

```
firebase deploy
```

Visit your app and try to post a new todo

The todo will not be added

If you check the logs from the google cloud console for the ssrServer function you'll see a time out

2021-05-26T23:43:25.085548695Z
ssrServerl9woaz02tpei Function execution took 60003 ms, finished with status: 'timeout'
Function execution took 60003 ms, finished with status: 'timeout'

![image](https://user-images.githubusercontent.com/481687/119759576-e0b44780-be7e-11eb-8d4d-fed6126aeb6e.png)

If you try it locally with `firebase serve` you'll get the same error with more detailed information in the terminal

![image](https://user-images.githubusercontent.com/481687/119759709-16f1c700-be7f-11eb-8cbd-2d7eb984c8f9.png)

I tried allocating 1GB of memory but the error persists

**Expected behavior**

The demo app should work fine, the post should be processed without errors

**Comment by jthegedus** [comment]
This is related to #87
