### ISSUE TITLE
Undefined bugs

### ISSUE THREAD

**Issue by treeder** [jthegedus/svelte-adapter-firebase#94]
**Describe the bug**

I'm getting errors during `firebase deploy`, with latest version:

```
> Using svelte-adapter-firebase
> Cannot read property 'minor' of undefined
TypeError: Cannot read property 'minor' of undefined
    at adapt (file:///workspaces/my-app2/node_modules/svelte-adapter-firebase/src/index.js:30:14)
```

Then I downgraded to 0.7.6 which is prior to [this](https://github.com/jthegedus/svelte-adapter-firebase/pull/80) to fix it and now I get:

```
> Using svelte-adapter-firebase
> utils.rimraf is not a function
TypeError: utils.rimraf is not a function
    at prepareEntrypoint (file:///workspaces/my-app2/node_modules/svelte-adapter-firebase/src/index.js:164:8)
```

I'm clearly doing something wrong, but not sure what...?

**Comment by jthegedus** [comment]
I made changes to the Adapter API in SvelteKit https://github.com/sveltejs/kit/pull/1559 which I have yet to update this adapter to use.

Since all this software is in Beta you must use specific versions of SvelteKit with this adapter. The version list is in the README.
